version: "3.8"

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1234
      POSTGRES_DB: AvatarWorldDB
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: products@axm.com
      PGADMIN_DEFAULT_PASSWORD: Test@1234
    ports:
      - "5000:80"
