/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\Unity_Work\Projects\webARTest\WebGLTest\client\public\models\env1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Env1(props) {
  const { nodes, materials } = useGLTF('/models/env1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cup.geometry} material={materials['Material.008']} position={[-0.209, 0.693, 0.054]} rotation={[Math.PI, 0, Math.PI]} scale={0.49} />
      <mesh geometry={nodes.Cup001.geometry} material={materials['Material.008']} position={[0.24, 0.693, 0.054]} rotation={[0, -0.482, 0]} scale={0.49} />
      <group position={[0.073, 0, 0.021]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials[' CoolGray8asdfasdas0fas16015.001']} />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials['Piso Amadeirado.001']} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials['BORRACHA PRETA.001']} />
        <mesh geometry={nodes.Plane001_5.geometry} material={materials['Metal preto.001']} />
        <mesh geometry={nodes.Plane001_6.geometry} material={materials['Black Plastic.001']} />
      </group>
      <group position={[-0.113, 0, 0.021]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials[' CoolGray8asdfasdas0fas16015.001']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Piso Amadeirado.001']} />
        <mesh geometry={nodes.Plane003_3.geometry} material={materials['BORRACHA PRETA.001']} />
        <mesh geometry={nodes.Plane003_4.geometry} material={materials['Metal preto.001']} />
        <mesh geometry={nodes.Plane003_5.geometry} material={materials['Black Plastic.001']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.010']} position={[0.014, 0.678, 0]} scale={[0.402, 0.015, 0.402]} />
      <mesh geometry={nodes.umprella.geometry} material={materials['Material.011']} position={[0.016, 1.761, -0.496]} rotation={[Math.PI, 0, Math.PI]} scale={2.902} />
      <mesh geometry={nodes.UMBRELLA_frame.geometry} material={materials['Material.012']} position={[0.016, 1.688, -0.496]} rotation={[Math.PI, 0, Math.PI]} scale={0.848} />
      <mesh geometry={nodes.umbrella_frame.geometry} material={materials['Material.012']} position={[0.016, 1.688, -0.496]} rotation={[Math.PI, 0, Math.PI]} scale={0.848} />
      <group position={[0.016, 0, -0.496]} rotation={[Math.PI, 0, Math.PI]} scale={0.848}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.014']} />
      </group>
      <mesh geometry={nodes.pole_objects.geometry} material={materials['Material.012']} position={[0.016, 1.676, -0.496]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.007} />
      <mesh geometry={nodes.pole_CRANK.geometry} material={materials['Material.012']} position={[0.018, 1.231, -0.496]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.007} />
      <mesh geometry={nodes.POLE.geometry} material={materials['Material.013']} position={[0.016, 0, -0.496]} rotation={[Math.PI, 0, Math.PI]} scale={0.848} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Grass.001']} position={[0, -0.987, 0.5]} scale={[5.017, 1.019, 5.017]} />
      <mesh geometry={nodes.restaurant_tablE_AND_BASE001.geometry} material={materials['Material.010']} position={[0.016, 0, 0.014]} rotation={[Math.PI, 0, Math.PI]} scale={[0.458, 0.848, 0.848]} />
      <mesh geometry={nodes.POLE001.geometry} material={materials['Material.013']} position={[0.016, 0, 0.014]} rotation={[Math.PI, 0, Math.PI]} scale={0.848} />
    </group>
  )
}

useGLTF.preload('/models/env1.glb')
